FROM python:3.13-slim
WORKDIR /root/code
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir coverage pytest pytest-black pytest-cov pytest-mock pytest-mypy
RUN pytest tests/ -v
