FROM python:3.10-slim
WORKDIR /root/code
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir numpy pandas packaging \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir pytest
CMD ["pytest", "test/", "-v", "--deselect=test/test_schema.py::OrderedSchema::test_mixed_columns"]
