FROM python:3.10-slim
WORKDIR /root/code
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir pytest pytest-cov \
 && pip install --no-cache-dir "protobuf<=3.20.3" "altair>=4.0,<5"
CMD ["pytest", "tests", "-v"]
