FROM python:3.13-slim
WORKDIR /root/code
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r test-requirements.txt \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir pytest
RUN pytest test/ -v
