FROM python:3.10-slim
WORKDIR /root/code
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r test-requirements.txt \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir pytest
CMD ["pytest", "test/", "-v"]
