FROM python:3.10-slim
WORKDIR /root/code
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir pytz \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir pytest
CMD pytest tests/ -v \
    --deselect=tests/bookmarks/test_service.py::TestBookmarkClient::test__set_bookmarks_failure \
    --deselect=tests/test_i18n.py::TestLocalizingFormatter::test_convert_field_datetime_default_locale \
    --deselect=tests/test_security_layer.py::Testextract_python_dict_from_x509::test_zombofant_net
