FROM python:3.8-slim
WORKDIR /root/code
COPY . .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -e . \
 && pip install --no-cache-dir pytest pytest-asyncio pytest-cov responses
CMD ["pytest", "tests/", "-v"]
